<?php

namespace Proxies\__CG__\Administrateur\AdminBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Evenement extends \Administrateur\AdminBundle\Entity\Evenement implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'titreEvent', 'dateDebEvent', 'dateFinEvent', 'typeEvent', 'description', 'bonPlan', 'adresse', 'id', 'idMembre');
        }

        return array('__isInitialized__', 'titreEvent', 'dateDebEvent', 'dateFinEvent', 'typeEvent', 'description', 'bonPlan', 'adresse', 'id', 'idMembre');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Evenement $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getTitreEvent()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitreEvent', array());

        return parent::getTitreEvent();
    }

    /**
     * {@inheritDoc}
     */
    public function getDateDebEvent()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateDebEvent', array());

        return parent::getDateDebEvent();
    }

    /**
     * {@inheritDoc}
     */
    public function getDateFinEvent()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateFinEvent', array());

        return parent::getDateFinEvent();
    }

    /**
     * {@inheritDoc}
     */
    public function getTypeEvent()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTypeEvent', array());

        return parent::getTypeEvent();
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', array());

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function getBonPlan()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBonPlan', array());

        return parent::getBonPlan();
    }

    /**
     * {@inheritDoc}
     */
    public function getAdresse()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdresse', array());

        return parent::getAdresse();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getIdMembre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdMembre', array());

        return parent::getIdMembre();
    }

    /**
     * {@inheritDoc}
     */
    public function setTitreEvent($titreEvent)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitreEvent', array($titreEvent));

        return parent::setTitreEvent($titreEvent);
    }

    /**
     * {@inheritDoc}
     */
    public function setDateDebEvent(\DateTime $dateDebEvent)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateDebEvent', array($dateDebEvent));

        return parent::setDateDebEvent($dateDebEvent);
    }

    /**
     * {@inheritDoc}
     */
    public function setDateFinEvent(\DateTime $dateFinEvent)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateFinEvent', array($dateFinEvent));

        return parent::setDateFinEvent($dateFinEvent);
    }

    /**
     * {@inheritDoc}
     */
    public function setTypeEvent($typeEvent)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTypeEvent', array($typeEvent));

        return parent::setTypeEvent($typeEvent);
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription($description)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', array($description));

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function setBonPlan($bonPlan)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBonPlan', array($bonPlan));

        return parent::setBonPlan($bonPlan);
    }

    /**
     * {@inheritDoc}
     */
    public function setAdresse($adresse)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdresse', array($adresse));

        return parent::setAdresse($adresse);
    }

    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', array($id));

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function setIdMembre(\Administrateur\AdminBundle\Entity\Membre $idMembre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdMembre', array($idMembre));

        return parent::setIdMembre($idMembre);
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', array());

        return parent::__toString();
    }

}
